import type { IconType } from "react-icons";
import { FaCss3Alt, FaServer } from "react-icons/fa";
import {
  MdAccountTree,
  MdAdminPanelSettings,
  MdBuild,
  MdCached,
  MdCode,
  MdDataObject,
  MdDevices,
  MdDns,
  MdHttps,
  MdHub,
  MdOutlinePolicy,
  MdOutlineSpeed,
  MdPassword,
  MdPhonelinkLock,
  MdRocketLaunch,
  MdSecurity,
  MdStorage,
  MdWeb,
} from "react-icons/md";
import {
  SiC,
  SiCloudflare,
  SiDocker,
  SiExpress,
  SiGit,
  SiGithub,
  SiHtml5,
  SiIntellijidea,
  SiJavascript,
  SiJsonwebtokens,
  SiLinux,
  SiMariadb,
  SiMongodb,
  SiMysql,
  SiNginx,
  SiNodedotjs,
  SiOpencode,
  SiOpenjdk,
  SiPhp,
  SiPostgresql,
  SiPostman,
  SiPrisma,
  SiPython,
  SiReact,
  SiRedis,
  SiSpringboot,
  SiSpringsecurity,
  SiSqlite,
  SiSupabase,
  SiTailwindcss,
  SiTypescript,
  SiVite,
  SiCplusplus,
} from "react-icons/si";
import {
  TbApi,
  TbArrowsExchange,
  TbBinaryTree,
  TbBrandCSharp,
  TbBug,
  TbCloudUpload,
  TbDatabaseImport,
  TbDatabaseSearch,
  TbFileText,
  TbKey,
  TbWorld,
} from "react-icons/tb";
import { VscVscode } from "react-icons/vsc";
import type { SkillIconId } from "@/types/portfolio";

const skillIconRegistry: Record<SkillIconId, IconType> = {
  backend: MdDns,
  frontend: MdWeb,
  databases: MdStorage,
  infrastructure: MdHub,
  security: MdSecurity,
  languages: MdCode,
  tools: MdBuild,
  springBoot: SiSpringboot,
  nodeJs: SiNodedotjs,
  express: SiExpress,
  restApi: TbApi,
  businessLogic: TbBinaryTree,
  react: SiReact,
  html5: SiHtml5,
  css3: FaCss3Alt,
  tailwindCss: SiTailwindcss,
  vite: SiVite,
  responsiveDesign: MdDevices,
  postgresql: SiPostgresql,
  mysql: SiMysql,
  mariadb: SiMariadb,
  mongodb: SiMongodb,
  redis: SiRedis,
  supabase: SiSupabase,
  sqlite: SiSqlite,
  prisma: SiPrisma,
  dataModeling: MdAccountTree,
  databaseIndexing: TbDatabaseSearch,
  queryOptimization: MdOutlineSpeed,
  transactions: TbArrowsExchange,
  databaseMigrations: TbDatabaseImport,
  backupStrategy: TbCloudUpload,
  docker: SiDocker,
  dockerCompose: MdAccountTree,
  linux: SiLinux,
  vps: FaServer,
  nginx: SiNginx,
  cloudflare: SiCloudflare,
  cloudflarePages: MdWeb,
  productionDeployment: MdRocketLaunch,
  logging: TbFileText,
  errorTracking: TbBug,
  caching: MdCached,
  cdn: TbWorld,
  authenticationAuthorization: TbKey,
  jwt: SiJsonwebtokens,
  springSecurity: SiSpringsecurity,
  roleBasedAccess: MdAdminPanelSettings,
  mfa: MdPhonelinkLock,
  rateLimiting: MdOutlineSpeed,
  cors: MdOutlinePolicy,
  https: MdHttps,
  secureCredentials: MdPassword,
  environmentVariables: MdDataObject,
  java: SiOpenjdk,
  javascript: SiJavascript,
  typescript: SiTypescript,
  python: SiPython,
  php: SiPhp,
  c: SiC,
  cplusplus: SiCplusplus,
  csharp: TbBrandCSharp,
  git: SiGit,
  github: SiGithub,
  intellijIdea: SiIntellijidea,
  visualStudioCode: VscVscode,
  postman: SiPostman,
  opencode: SiOpencode,
};

export function SkillGlyph({ icon }: { icon: SkillIconId }) {
  const Icon = skillIconRegistry[icon];
  return <Icon aria-hidden="true" focusable="false" />;
}
